# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main, 17-publish-notebooks ]
  pull_request:
    branches: [ main, 17-publish-notebooks ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  josepaper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Open Journals PDF Generator
        uses: openjournals/openjournals-draft-action@v.1.0

  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get -qq update --allow-releaseinfo-change -y && apt-get -qq install -y pandoc ffmpeg &&
        pip install matplotlib scipy filterpy pandas tqdm notebook nbsphinx-link nbsphinx furo numpydoc nb2plots sphinx-autoapi numpy markupsafe && pip install -U sphinx"
        docs-folder: docs

    # # Great extra actions to compose with:
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/_build/html/    
    # Publish built docs to gh-pages branch.
    - name: Commit documentation changes
      run: |
        git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force: true
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}